module.exports = [
	{
		heroid: 0,
		name: 'lucio',
		img: 'http://www.heroesfire.com/images/hero/portrait/lucio.png',
		seotitle: 'Heroes Hero Lúcio :: Heroes of the Storm Lúcio stats and strategy.',
		seodesc: 'Lúcio: Heroes Heroes wiki and database. Explore Heroes of the Storm',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'Freedom Fighting DJ',
		role: 'support',
		universe: 'OVERWATCH',
		health: '1508 (+0.04)',
		regen: '3.14028	(+0.040)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '0.80',
		damage: '24.96 (+0.04)',
		about: 'Freedom Fighting DJ, is a ranged support hero from Overwatch universe. From the streets of Rio to the clubs on King\'s Row, Lúcio\'s beats bring the party to life, and drive the people to action. Now he\'s on tour in the Nexus, ready to Break it down, and to continue fighting for what\'s right. He is a highly mobile Support who constantly heals or grants Movement Speed to all allies around him.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/we-move-together.png', abilname: 'We move together' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/chase-the-bass.png', abilname: 'Chase the bass' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/party-mix.png', abilname: 'Party mix' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sound-barrier-talent.png', abilname: 'Sound barrier' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/back-in-the-mix.png', abilname: 'Back in the mix' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/rejuvenesc-ncia.png', abilname: 'Rejuvenesc ncia' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/synaesthesia-auditiva.png', abilname: 'Synaesthesia auditiva' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/we-move-together.png', abilname: 'We move together' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/maximum-tempo.png', abilname: 'Maximum tempo' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/accelerando.png', abilname: 'Accelerando' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/slip.png', abilname: 'Slip' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/subwoofer.png', abilname: 'Subwoofer' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/off-the-wall.png', abilname: 'Off the wall' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/chase-the-bass.png', abilname: 'Chase the bass' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/party-mix.png', abilname: 'Party mix' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sonic-amplifier.png', abilname: 'Sonic amplifier' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/boombox-talent.png', abilname: 'Boombox talent' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sound-barrier-talent.png', abilname: 'Sound barrier' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/reverse-amp-talent.png', abilname: 'Reverse amp' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/beat-mixing.png', abilname: 'Beat mixing' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/cant-stop-wont-stop.png', abilname: 'Cant stop' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hard-style.png', abilname: 'Hard style' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/back-in-the-mix.png', abilname: 'Back in the mix' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/rejuvenesc-ncia.png', abilname: 'Rejuvenesc ncia' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bring-it-together.png', abilname: 'Bring it together' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/up-the-frequency.png', abilname: 'Up the frequency' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bossa-nova.png', abilname: 'Bossa nova' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nonstop-remix.png', abilname: 'Onstop remix' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bonus-track.png', abilname: 'Bonus track' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/synaesthesia-auditiva.png', abilname: 'Synaesthesia auditiva' },
		],
	},

	{
		heroid: 1,
		name: 'valeera',
		img: 'http://www.heroesfire.com/images/hero/portrait/valeera.png',
		seotitle: 'Heroes Hero Valeera :: Heroes of the Storm Valeera stats and strategy.',
		seodesc: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes',
		title: 'SHADOW OF THE UNCROWNED',
		role: 'assasin',
		universe: 'StarCraft',
		health: '1508 (+0.04)',
		regen: '3.14028	(+0.040)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '0.80',
		damage: '24.96 (+0.04)',
		about: 'Valeera Sanguinar, Shadow of the Uncrowned, is a melee assassin hero from the Warcraft universe. For a time, the gladiator Valeera Sanguinar served dutifully as one of Varian Wrynn\'s personal bodyguards. Now, her shadowy skills find her a natural fit within the secretive rogue order, the Uncrowned, in their fight against the Legion. She is a tricky assassin who can gain access to different abilities while stealthed, and builds combo points to eviscerate her opponents.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/vigor.png', abilname: 'Vigor' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/initiative.png', abilname: 'Initiative' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/assassinate.png', abilname: 'Assassinate' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/cloak-of-shadows-talent.png', abilname: 'Cloak of shadows' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/death-from-above.png', abilname: 'Death from above' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/expose-armor.png', abilname: 'Expose armor' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nightslayer.png', abilname: 'Nightslayer' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/vigor.png', abilname: 'Vigor' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/subtlety.png', abilname: 'Subtlety' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/combat-readiness.png', abilname: 'Combat readiness' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/crippling-poison-talent.png', abilname: 'Crippling poison' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/relentless-strikes.png', abilname: 'Relentless strikes' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hemorrhage.png', abilname: 'Hemorrhage' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/initiative.png', abilname: 'Initiative' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/wound-poison-talent.png', abilname: 'Wound poison' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/mutilate.png', abilname: 'Mutilate' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/fatal-finesse.png', abilname: 'Fatal finesse' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/slice-and-dice.png', abilname: 'Slice and dice' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/assassinate.png', abilname: 'Assassinate' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/smoke-bomb-talent.png', abilname: 'Smoke bomb' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/cloak-of-shadows-talent.png', abilname: 'Cloak of shadows' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/elusiveness.png', abilname: 'Elusiveness' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/death-from-above.png', abilname: 'Death from above' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/blind.png', abilname: 'Blind' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/strangle.png', abilname: 'Strangle' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/seal-fate.png', abilname: 'Seal fate' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/rupture.png', abilname: 'Rupture' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/expose-armor.png', abilname: 'Expose armor' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/thistle-tea-talent.png', abilname: 'Thistle tea' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenaline-rush-talent.png', abilname: 'Adrenaline rush' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/enveloping-shadows.png', abilname: 'Enveloping shadows' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nightslayer.png', abilname: 'Nightslayer' },
		],
	},

	{
		heroid: 2,
		name: 'zuljin',
		img: 'http://www.heroesfire.com/images/hero/portrait/zuljin.png',
		seotitle: 'Heroes Hero Zul\'jin :: Heroes of the Storm Zul\'jin stats and strategy.',
		seodesc: 'Zul\'jin: Heroes Heroes wiki and database. Explore Heroes of the Storm',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'WARLORD OF THE AMANI',
		role: 'assasin',
		universe: 'Warcraft',
		health: '1508 (+0.04)',
		regen: '3.14028	(+0.040)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '0.80',
		damage: '24.96 (+0.04)',
		about: 'Zuljin the Warlord of the Amani, is a ranged assassin hero from the Warcraft universe. He is an aggressive ranged attacker who gets stronger as his health decreases. Can regenerate health after fights.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/you-want-axe.png', abilname: 'You want axe' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/let-the-killing-begin.png', abilname: 'Let the killing' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/vicious-assault.png', abilname: 'Vicious assault' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/tazdingo-talent.png', abilname: 'Tazdingo talent' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/forest-medicine.png', abilname: 'Forest medicine' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ferocity.png', abilname: 'Ferocity' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/amani-resilience.png', abilname: 'Amani resilience' },
		],

		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/boneslicer.png', abilname: 'Boneslicer' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/arcanite-axes.png', abilname: 'Arcanite axes' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/you-want-axe.png', abilname: 'You want axe' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/trolls-blood.png', abilname: 'Trolls blood' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/let-the-killing-begin.png', abilname: 'Let the killing' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/headhunter-talent.png', abilname: 'Headhunter talent' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/vicious-assault.png', abilname: 'Vicious assault' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/wrong-place-wrong-time.png', abilname: 'Wrong place' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/recklessness.png', abilname: 'Recklessness' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/tazdingo-talent.png', abilname: 'Tazdingo talent' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/guillotine-talent.png', abilname: 'Guillotine talent' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/eye-of-zuljin.png', abilname: 'Eye of zuljin' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/forest-medicine.png', abilname: 'Forest medicine' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/voodoo-shuffle-talent.png', abilname: 'Voodoo shuffle' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/swirling-death.png', abilname: 'Swirling death' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lacerate.png', abilname: 'Lacerate' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ferocity.png', abilname: 'Ferocity' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/amani-resilience.png', abilname: 'Amani resilience' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/buzzsaw.png', abilname: 'Buzzsaw' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ensnare-talent.png', abilname: 'Ensnare talent' },
		],
	},

	{
		heroid: 3,
		name: 'abathur',
		img: 'https://www.heroesfire.com/images/hero/portrait/abathur.png',
		seotitle: 'Heroes Hero Abathur :: Heroes of the Storm Abathur stats and strategy.',
		seodesc: 'Abathur: Heroes Heroes wiki and database. Explore Heroes of the Storm',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'EVOLUTION MASTER',
		role: 'SPECIALIST',
		universe: 'StarCraft',
		health: '712 (+4.0%)',
		regen: '1.48 (+4.0%)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '1.43',
		damage: '27	(+4.0%)',
		about: 'Abathur, the Evolution Master of Kerrigan\'s Swarm, works ceaselessly to improve the zerg from the genetic level up. His hate for chaos and imperfection almost rivals his hatred of pronouns.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/pressurized-glands.png', abilname: 'Pressurized Glands' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenal-overload.png', abilname: 'Adrenal Overload' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/needlespine.png', abilname: 'Needlespine' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ultimate-evolution-talent.png', abilname: 'Ultimate Evolution' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soma-transference.png', abilname: 'Soma Transferance' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soma-transference.png', abilname: 'Envenomed Spikes' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenal-overload.png', abilname: 'Hivemind' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/pressurized-glands.png', abilname: 'Pressurized Glands' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/survival-instincts.png', abilname: 'Survival Instincts' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/regenerative-microbes.png', abilname: 'Regenerative Microbes' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/envenomed-nest.png', abilname: 'Envenomed Nest' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/prolific-dispersal.png', abilname: 'Prolific Dispersal' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ballistospores.png', abilname: 'Ballistospores' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sustained-carapace.png', abilname: 'Sustained Carapace' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenal-overload.png', abilname: 'Adrenal Overload' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/needlespine.png', abilname: 'Needlespine' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/vile-nest.png', abilname: 'Vile Nest' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/networked-carapace.png', abilname: 'Networked Carapace' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/calldown-mule-talent.png', abilname: 'Calldown: MULE' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ultimate-evolution-talent.png', abilname: 'Ultimate Evolution' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/abilities/evolve-monstrosity.png', abilname: 'Evolve Monstrosity' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/assault-strain.png', abilname: 'Assault Strain' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bombard-strain.png', abilname: 'Bombard Strain' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/spatial-efficiency.png', abilname: 'Spatial Efficiency' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soma-transference.png', abilname: 'Soma Transferance' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soma-transference.png', abilname: 'Envenomed Spikes' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenaline-boost.png', abilname: 'Adrenaline Boost' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/locust-brood-talent.png', abilname: 'Locust Brood' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/volatile-mutation.png', abilname: 'Volatile Mutation' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ultimate-evolution-talent.png', abilname: 'Evolution Link' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/evolution-complete.png', abilname: 'Evolution Complete' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/adrenal-overload.png', abilname: 'Hivemind' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/locust-nest-talent.png', abilname: 'Locust Nest' },
		],
	},

	{
		heroid: 4,
		name: 'illidan',
		img: 'https://www.heroesfire.com/images/hero/portrait/illidan.png',
		seotitle: 'Heroes Hero Illidan :: Heroes of the Storm Illidan stats and strategy.',
		seodesc: 'Illidan: Heroes Heroes wiki and database. Explore Heroes of the Storm',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'THE BETRAYER',
		role: 'ASSASSIN',
		universe: 'WARCRAFT',
		health: '1,716 (+4.0%)',
		regen: '3.58 (+4.0%)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '1.82',
		damage: '81	(+4.0%)',
		about: 'Illidan Stormrage, the first Demon Hunter, betrayed his people and created a new Well of Eternity after the demonic invasion of Azeroth. Now Illidan lords over Outland slaying unsuitably prepared Heroes who venture into his domain.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/shadow-shield.png', abilname: 'Shadow Shield' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/immolation.png', abilname: 'Immolation' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/first-aid-talent.png', abilname: 'First Aid' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/first-aid-talent.png', abilname: 'First Aid' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sixth-sense-illidan.png', abilname: 'Giant Killer' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/blood-for-blood-talent.png', abilname: 'Blood for Blood' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bolt-of-the-storm-talent.png', abilname: 'Bolt of the Storm' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/immolation.png', abilname: 'Immolation' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/battered-assault.png', abilname: 'Battered assault' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/unending-hatred.png', abilname: 'Nending hatred' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/rapid-chase.png', abilname: 'Rapid chase' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/friend-or-foe.png', abilname: 'Friend or foe' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/unbound.png', abilname: 'Unbound' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/reflexive-block.png', abilname: 'Reflexive block' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/thirsting-blade.png', abilname: 'Thirsting blade' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hunters-onslaught.png', abilname: 'Hunters onslaught' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/metamorphosis-talent.png', abilname: 'Metamorphosis talent' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/the-hunt-talent.png', abilname: 'The hunt talent' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nimble-defender.png', abilname: 'Nimble defender' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/elusive-strike.png', abilname: 'Elusive strike' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sixth-sense-illidan.png', abilname: 'Sixth sense illidan' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/marked-for-death.png', abilname: 'Marked for death' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/fiery-brand.png', abilname: 'Fiery brand' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/blades-of-azzinoth-talent.png', abilname: 'Blades' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/demonic-form.png', abilname: 'Demonic form' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nowhere-to-hide.png', abilname: 'Nowhere to hide' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/nexus-blades.png', abilname: 'Nexus blades' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bolt-of-the-storm-talent.png', abilname: 'Storm talent' },
		],
	},

	{
		heroid: 5,
		name: 'diablo',
		img: 'https://www.heroesfire.com/images/hero/portrait/diablo.png',
		seotitle: 'Heroes Hero Diablo :: Heroes of the Storm Diablo stats and strategy.',
		seodesc: 'Diablo: Heroes Heroes wiki and database. Explore Heroes of the Storm',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'LORD OF TERROR',
		role: 'WARRIOR',
		universe: 'diablo',
		health: '2,670 (+4.0%)',
		regen: '3.58 (+4.0%)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '0.91',
		damage: '109 (+4.0%)',
		about: 'Known in the ancient tongue as Al\'Diabolos, the Prime Evil of Terror, the Demon Lord Diablo seeks to claim the world of Sanctuary for the Burning Hells. His victims are innumerable, his schemes unknowable, and his gender... malleable.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/devils-due.png', abilname: 'Devils due' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/fire-devil.png', abilname: 'Fire devil' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soul-steal.png', abilname: 'Soul steal' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/apocalypse-talent.png', abilname: 'Apocalypse' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/siphon-the-dead-talent.png', abilname: 'Siphon the dead' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/imposing-presence-talent.png', abilname: 'Imposing presence' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lord-of-terror-talent.png', abilname: 'Lord of terror' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/bulwark.png', abilname: 'Bulwark' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/devils-due.png', abilname: 'Devils due' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/life-leech.png', abilname: 'Life leech' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/from-the-shadows.png', abilname: 'From the shadows' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/speed-demon.png', abilname: 'Speed demon' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/demonic-strength.png', abilname: 'Demonic strength' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soul-feast.png', abilname: 'Soul feast' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/soul-shield.png', abilname: 'Soul shield' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/diabolical-momentum.png', abilname: 'Diabolical momentum' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/apocalypse-talent.png', abilname: 'Apocalypse' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lightning-breath-talent.png', abilname: 'Lightning breath' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/devastating-charge.png', abilname: 'Devastating charge' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/fire-devil.png', abilname: 'Fire devil' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hellfire.png', abilname: 'Hellfire' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/debilitating-flames.png', abilname: 'Debilitating flames' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/domination.png', abilname: 'Domination' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/fearful-presence-talent.png', abilname: 'Fearful-presence' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/dying-breath.png', abilname: 'Dying breath' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hellstorm.png', abilname: 'Hellstorm' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lord-of-terror-talent.png', abilname: 'Lord of terror' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hellgate-talent.png', abilname: 'Hellgate' },
		],
	},

	{
		heroid: 6,
		name: 'Alarak',
		img: 'http://www.heroesfire.com/images/hero/portrait/alarak.png',
		seotitle: 'Alarak Build Guide &ldquo;The hour of my vengeance has come.&rdquo; - Heroes of the Storm',
		seodesc: 'The ultimate guide to playing Alarak in Heroes of the Storm: talent builds, playstyle, matchups, maps, etc.',
		seokey: 'Heroes of the Storm, Heroes, Heroes Guides, Heroes Builds, Heroes of the Storm Builds, Heroes of the Storm Guides, MOBA, HeroesFire, Strategy Guides, Fan Site,  Heroes Wiki, Heroes of the Storm Wiki, Heroes of the Storm Database, Heroes Database, Heroes, MOBAFire Network',
		title: 'HIGHLORD',
		role: 'assasin',
		universe: 'StarCraft',
		health: '1976 (+0.04)',
		regen: '4.11528	(+0.040)',
		mana: '500	(+10)',
		manaregen: '3 (+0.098)',
		atack: '1.00',
		damage: '145.6 (+0.04)',
		about: 'Not all heroes are born of altruism... some, like Alarak, simply desire vengeance. As the new Highlord of the Tal\'darim, Alarak leads his people to a destiny free of the corrupt influence of the fallen xel\'naga, Amon.',
		guide: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/power-conduit.png', abilname: 'Power Conduit' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/power-conduit.png', abilname: 'Extended Lightning' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/power-conduit.png', abilname: 'Endless Energy' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/deadly-charge-talent.png', abilname: 'Deadly Charge' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/pure-malice.png', abilname: 'Pure Malice' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/power-conduit.png', abilname: 'Negatively Charged' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/counter-strike-talent.png', abilname: 'Counter-Strike' },
		],
		skill: [
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/sustaining-power.png', abilname: 'Sustaining power' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/extended-lightning.png', abilname: 'Extended lightning' },
			{ level: 1, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/ruthless-momentum.png', abilname: 'Ruthless momentum' },

			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/chaos-reigns.png', abilname: 'Chaos reigns' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/negatively-charged.png', abilname: 'Negatively charged' },
			{ level: 4, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/show-of-force.png', abilname: 'Show of force' },

			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/dissonance.png', abilname: 'Dissonance' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hindered-motion.png', abilname: 'Hindered motion' },
			{ level: 7, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/applied-force.png', abilname: 'Applied force' },

			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/deadly-charge-talent.png', abilname: 'Deadly charge' },
			{ level: 10, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/counter-strike-talent.png', abilname: 'Counter strike' },

			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/blade-of-the-highlord.png', abilname: 'Blade of the highlord' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/pure-malice.png', abilname: 'Pure malice' },
			{ level: 13, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/rite-of-rakshir-talent.png', abilname: 'Rite of rakshir' },

			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lethal-onslaught.png', abilname: 'Lethal onslaught' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/lightning-barrage.png', abilname: 'Lightning barrage' },
			{ level: 16, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/mocking-strikes.png', abilname: 'Mocking strikes' },

			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/counter-strike-talent.png', abilname: 'Counter strike' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/deadly-charge-talent.png', abilname: 'Deadly charge' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/last-laugh-talent.png', abilname: 'Last laugh' },
			{ level: 20, img: 'http://www.heroesfire.com/images/wikibase/icon/talents/hasty-bargain-talent.png', abilname: 'Hasty bargain' },
		],
	}



]

